### PR TITLE
Patrolling Monster Vision

### PR DESCRIPTION
**Pull request by kenmiller521**
Script for the vision of the patrolling monster. Uses line cast for the
vision of the monster. When the player collides with the line cast the
monster will do something(later to be determined). The line cast will
reverse when the patrolling monster reverses movement.

### CODE REVIEW

**Comment by ARGutierrez** [comment]
Hey Ken, this seems functional! Just going to leave some feedback. Doesn't mean it won't get accepted, but its stuff you can fix if you have time.
- Pull linecast distance out to a variable instead of hard-coding 4.0f. When you flip the monster, you can just multiply this through by -1 to make sure it changes direction.
- Consider that any movement related code will probably be in the main PatrollingMonster script and not in the script related to monster vision specifically. In fact, those my be combined at some point since there's not a whole lot more that needs to be done to detect the player.
- I'm assuming you made the player game object public so that you can assign it in the inspector? That's a perfectly fine solution, but for the sake of code clarity, I find it best to do that through code. So in the start function, you can do a FindGameObjectWithTag and look for the player tag.

**Comment by kenmiller521** [comment]
Thank you for the feedback! Once I make changes how would I submit them? Would I just make another pull request?

**Comment by ARGutierrez** [comment]
Correct! Just feel free to make changes, then make another pull request.

**Comment by kenmiller521** [comment]
I added a new commit to my branch but I don't see a button to make a new pull request in the GitHub Desktop app. Would just making a new commit to the same pull request just update the pull request? Or would I hit the "revert" button?

**Comment by Darkchicken** [comment]
There shouldn't be any need to revert anything. You just can't have
multiple pull requests active. I'll delete the original one and then you
should be ok

**Comment by Darkchicken** [comment]
Ok, it's closed. Try now

**Pull request closed without merging**
